scripts/*-bump: support direct 'make <target>'

diff --git a/scripts/bootloader-bump b/scripts/bootloader-bump
--- a/scripts/bootloader-bump
+++ b/scripts/bootloader-bump
@@ -7,22 +7,27 @@ usage ()
 {
 	printf "\nusage: bootloader-bump <command>\n\n"
 	printf "<command>\n"
-	printf "\tbuild   - Purge and Build\n"
-	printf "\tupdate  - Clean and Build\n"
-	printf "\t*config - {g,menu,n,old}config\n\n"
+	printf "\tmake <target> - Direct make target\n"
+	printf "\tbuild         - Purge and Build\n"
+	printf "\tupdate        - Clean and Build\n"
+	printf "\t*config       - {g,menu,n,old}config\n\n"
 }
 
 do_make ()
 {
-	case $1 in
+	printf "\n[$1]\n"
+	case $2 in
+	make)
+		ET_BOARD=$1 make bootloader-$3
+		;;
 	*config)
-		ET_BOARD=$2 make bootloader-$1
+		ET_BOARD=$1 make bootloader-$2
 		;;
 	update)
-		ET_BOARD=$2 make bootloader-$1
+		ET_BOARD=$1 make bootloader-$2
 		;;
 	build)
-		ET_BOARD=$2 make bootloader-purge bootloader
+		ET_BOARD=$1 make bootloader-purge bootloader
 		;;
 	*)
 		;;
@@ -47,6 +52,13 @@ fi
 
 # validate first positional argument
 case $1 in
+make)
+	if [ -e $2 ]; then
+		printf "Missing 'make' arguments!\n"
+		usage
+		exit 1
+	fi
+	;;
 *config | update | build)
 	;;
 *)
@@ -75,7 +87,7 @@ for n in `ls boards`; do
 		case $b in
 		u-boot-*)
 			board=`echo $b | grep -Po 'u-boot-\K[^\n]*'`
-			if ! do_make $1 $board; then
+			if ! do_make $board "$@"; then
 				printf "etinker $0 failed!\n"
 				exit 1
 			fi
diff --git a/scripts/kernel-bump b/scripts/kernel-bump
--- a/scripts/kernel-bump
+++ b/scripts/kernel-bump
@@ -7,22 +7,27 @@ usage ()
 {
 	printf "\nusage: kernel-bump <command> [-rt]\n\n"
 	printf "<command>\n"
-	printf "\tbuild   - Purge and Build\n"
-	printf "\tupdate  - Clean and Build\n"
-	printf "\t*config - {g,menu,n,old}config\n\n"
+	printf "\tmake <target> - Direct make target\n"
+	printf "\tbuild         - Purge and Build\n"
+	printf "\tupdate        - Clean and Build\n"
+	printf "\t*config       - {g,menu,n,old}config\n\n"
 }
 
 do_make ()
 {
-	case $1 in
+	printf "\n[$1]\n"
+	case $2 in
+	make)
+		ET_BOARD=$1 make kernel-$3
+		;;
 	*config)
-		ET_BOARD=$2 make kernel-$1
+		ET_BOARD=$1 make kernel-$2
 		;;
 	update)
-		ET_BOARD=$2 make kernel-$1 overlay-$1
+		ET_BOARD=$1 make kernel-$2 overlay-$2
 		;;
 	build)
-		ET_BOARD=$2 make kernel-purge overlay-update
+		ET_BOARD=$1 make kernel-purge overlay-update
 		;;
 	*)
 		;;
@@ -38,6 +43,16 @@ is_virtual ()
 	fi
 }
 
+is_rt ()
+{
+	for param in $@; do
+		if [ "$param" = "-rt" ]; then
+			return 0
+		fi
+	done
+	return 1
+}
+
 # verify first positional argument
 if [ -e $1 ]; then
 	printf "Missing arguments!\n"
@@ -47,6 +62,13 @@ fi
 
 # validate first positional argument
 case $1 in
+make)
+	if [ -e $2 ]; then
+		printf "Missing 'make' arguments!\n"
+		usage
+		exit 1
+	fi
+	;;
 *config | update | build)
 	;;
 *)
@@ -74,10 +96,10 @@ for n in `ls boards`; do
 	fi
 
 	# realtime boards
-	if [ "$2" = "-rt" ]; then
+	if is_rt "$@"; then
 		case $n in
 		aml-s905x-cc-rt | ls1043ardb-rt)
-			if ! do_make $1 $n; then
+			if ! do_make $n "$@"; then
 				printf "etinker $0 failed!\n"
 				exit 1
 			fi
@@ -91,7 +113,7 @@ for n in `ls boards`; do
 	# baseline boards
 	case $n in
 	am335x-pocketbeagle | aml-s905x-cc | ls1043ardb | pynq-z2 | sama5d3-xpld)
-		if ! do_make $1 $n; then
+		if ! do_make $n "$@"; then
 			printf "etinker $0 failed!\n"
 			exit 1
 		fi
diff --git a/scripts/rootfs-bump b/scripts/rootfs-bump
--- a/scripts/rootfs-bump
+++ b/scripts/rootfs-bump
@@ -7,22 +7,24 @@ usage ()
 {
 	printf "\nusage: rootfs-bump <command>\n\n"
 	printf "<command>\n"
-	printf "\tbuild   - Purge and Build\n"
-	printf "\tupdate  - Clean and Build\n"
-	printf "\t*config - {g,menu,n,old}config\n\n"
+	printf "\tmake <target> - Direct make target\n"
+	printf "\tbuild         - Purge and Build\n"
+	printf "\tupdate        - Clean and Build\n"
+	printf "\t*config       - {g,menu,n,old}config\n\n"
 }
 
 do_make ()
 {
-	case $1 in
-	*config)
-		ET_BOARD=$2 make rootfs-$1
+	printf "\n[$1]\n"
+	case $2 in
+	*config | make)
+		ET_BOARD=$1 make rootfs-$3
 		;;
 	update)
-		ET_BOARD=$2 make rootfs-$1 kernel-$1 overlay-$1
+		ET_BOARD=$1 make rootfs-$2 kernel-$2 overlay-$2
 		;;
 	build)
-		ET_BOARD=$2 make rootfs-purge rootfs kernel-update overlay-update
+		ET_BOARD=$1 make rootfs-purge rootfs kernel-update overlay-update
 		;;
 	*)
 		;;
@@ -47,6 +49,13 @@ fi
 
 # validate first positional argument
 case $1 in
+make)
+	if [ -e $2 ]; then
+		printf "Missing 'make' arguments!\n"
+		usage
+		exit 1
+	fi
+	;;
 *config | update | build)
 	;;
 *)
@@ -70,10 +79,10 @@ for n in `ls boards`; do
 		continue
 	fi
 
-	# baseline boards
+	# boards with a Linux root filesystem
 	case $n in
 	am335x-pocketbeagle* | aml-s905x-cc* | ls1043ardb* | pynq-z2* | sama5d3-xpld*)
-		if ! do_make $1 $n; then
+		if ! do_make $n "$@"; then
 			printf "etinker $0 failed!\n"
 			exit 1
 		fi
diff --git a/scripts/toolchain-bump b/scripts/toolchain-bump
--- a/scripts/toolchain-bump
+++ b/scripts/toolchain-bump
@@ -7,18 +7,23 @@ usage ()
 {
 	printf "\nusage: toolchain-bump <command>\n\n"
 	printf "<command>\n"
-	printf "\tbuild   - Purge and Build\n"
-	printf "\t*config - {g,menu,n,old,savedef}config\n\n"
+	printf "\tmake <target> - Direct make target\n"
+	printf "\tbuild         - Purge and Build\n"
+	printf "\t*config       - {g,menu,n,old,savedef}config\n\n"
 }
 
 do_make ()
 {
-	case $1 in
+	printf "\n[$1]\n"
+	case $2 in
+	make)
+		ET_BOARD=$1 make toolchain-$3
+		;;
 	*config)
-		ET_BOARD=$2 make toolchain-$1
+		ET_BOARD=$1 make toolchain-$2
 		;;
 	build)
-		ET_BOARD=$2 ET_PURGE=yes make toolchain-purge toolchain
+		ET_BOARD=$1 ET_PURGE=yes make toolchain-purge toolchain
 		;;
 	*)
 		;;
@@ -43,6 +48,13 @@ fi
 
 # validate first positional argument
 case $1 in
+make)
+	if [ -e $2 ]; then
+		printf "Missing 'make' arguments!\n"
+		usage
+		exit 1
+	fi
+	;;
 build | *config)
 	;;
 *)
@@ -69,7 +81,7 @@ for n in `ls boards`; do
 	# baseline boards for supported toolchains
 	case $n in
 	ek-tm4c123gxl | arm-bare-metal | am335x-pocketbeagle | aml-s905x-cc | pynq-z2 | sama5d3-xpld)
-		if ! do_make $1 $n; then
+		if ! do_make $n "$@"; then
 			printf "etinker $0 failed!\n"
 			exit 1
 		fi
