kernel: use ET_KERNEL_VARIANT for '-rt' board builds

diff --git a/scripts/kernel-bump b/scripts/kernel-bump
--- a/scripts/kernel-bump
+++ b/scripts/kernel-bump
@@ -45,16 +45,6 @@ is_virtual ()
 	fi
 }
 
-is_rt ()
-{
-	for param in $@; do
-		if [ "$param" = "-rt" ]; then
-			return 0
-		fi
-	done
-	return 1
-}
-
 # verify first positional argument
 if [ -z "$1" ]; then
 	printf "Missing arguments!\n"
@@ -97,21 +87,6 @@ for n in `ls ${ET_DIR}/boards`; do
 		continue
 	fi
 
-	# realtime boards
-	if is_rt "$@"; then
-		case $n in
-		aml-s905x-cc-rt | ls1043ardb-rt | omap3-evm-rt)
-			if ! do_make $n "$@"; then
-				printf "etinker $0 failed!\n"
-				exit 1
-			fi
-			;;
-		*)
-			;;
-		esac
-		continue
-	fi
-
 	# baseline boards
 	case $n in
 	am335x-pocketbeagle | aml-s905x-cc | ls1012afrdm | ls1043ardb | omap3-evm | pynq-z2-xlnx | pynq-z2 | sama5d3-xpld)
@@ -123,6 +98,19 @@ for n in `ls ${ET_DIR}/boards`; do
 		if ! do_make $n "$@"; then
 			printf "etinker $0 failed!\n"
 			exit 1
+			# realtime builds
+			case $n in
+			am335x-pocketbeagle | aml-s905x-cc | ls1043ardb)
+				export ET_KERNEL_VARIANT="-rt"
+				if ! do_make $n "$@"; then
+					printf "etinker $0 failed!\n"
+					exit 1
+				fi
+				unset ET_KERNEL_VARIANT
+				;;
+			*)
+				;;
+			esac
 		fi
 		;;
 	*)
