scripts/host/setup: create 'generally required' section

diff --git a/scripts/host/setup b/scripts/host/setup
--- a/scripts/host/setup
+++ b/scripts/host/setup
@@ -40,6 +40,7 @@ if which apt &> /dev/null; then
 		unzip \
 		wget \
 		xz-utils
+
 	if ! [ "$?" = "0" ]; then
 		printf "APT Install Error! [ crosstool-ng ]\n"
 		exit 1
@@ -72,25 +73,49 @@ if which apt &> /dev/null; then
 		libglib2.0-dev \
 		libgtk-3-dev \
 		libmpc-dev \
+		libpython3-all-dev \
 		libsecret-1-dev \
 		libssl-dev \
 		libxss-dev \
 		mercurial \
 		perl \
 		python3-aiohttp \
-		python3-argparse-addons \
 		python3-matplotlib \
-		python3-pip \
 		rsync \
 		sed \
 		subversion \
 		tar \
 		u-boot-tools \
 		w3m \
-		which \
-		x11-utils
+		which
+
 	if ! [ "$?" = "0" ]; then
 		printf "APT Install Error! [ buildroot ]\n"
+		exit 1
+	fi
+
+	# generally required
+	sudo apt install -y \
+		libc-dev-bin \
+		libdebuginfod-dev \
+		python3-all-dev \
+		python3-argparse-addons \
+		python3-cryptography \
+		python3-deprecated \
+		python3-deprecation \
+		python3-pyelftools \
+		python3-jsonschema \
+		python3-jsonschema-specifications \
+		python3-pip \
+		python3-setuptools \
+		python3-virtualenv \
+		python3-yaml \
+		python-is-python3 \
+		x11-utils \
+		yamllint
+
+	if ! [ "$?" = "0" ]; then
+		printf "APT Install Error! [ general ]\n"
 		exit 1
 	fi
 
@@ -124,7 +149,6 @@ if which apt &> /dev/null; then
 			iproute2 \
 			less \
 			libasound2-dev \
-			libc-dev-bin \
 			libelf-dev \
 			libexpat1-dev \
 			libfreetype-dev \
@@ -181,11 +205,6 @@ if which apt &> /dev/null; then
 			patchelf \
 			pax \
 			pkg-config \
-			python-is-python3 \
-			python3-cryptography \
-			python3-pyelftools \
-			python3-jsonschema python3-jsonschema-specifications \
-			python3-all-dev libpython3-all-dev \
 			rlwrap \
 			rpm \
 			schroot \
@@ -211,9 +230,9 @@ if which apt &> /dev/null; then
 			whois \
 			xmlto \
 			xvfb \
-			yamllint \
 			zip \
 			zlib1g-dev
+
 		if ! [ "$?" = "0" ]; then
 			printf "APT Install Error! [ dev ]\n"
 			exit 1
@@ -265,6 +284,7 @@ if which pacman &> /dev/null && [ -n "${is_arch}" ] || [ -n "${is_artix}" ]; the
 		unzip \
 		wget \
 		xz
+
 	if ! [ "$?" = "0" ]; then
 		printf "pacman Install Error! [ crosstool-ng ]\n"
 		exit 1
@@ -301,26 +321,42 @@ if which pacman &> /dev/null && [ -n "${is_arch}" ] || [ -n "${is_artix}" ]; the
 		multilib-devel \
 		perl \
 		python-aiohttp \
-		python-argparse-manpage \
-		python-build \
-		python-deprecated \
-		python-deprecation \
-		python-installer \
 		python-matplotlib \
-		python-pip \
-		python-setuptools \
-		python-uv \
-		python-virtualenv \
-		rpcsvc-proto \
 		sed \
 		subversion \
 		tar \
 		uboot-tools \
 		w3m \
-		which \
-		xorg-xlsclients
+		which
+
 	if ! [ "$?" = "0" ]; then
 		printf "pacman Install Error! [ buildroot ]\n"
+		exit 1
+	fi
+
+	# generally required
+	sudo pacman -S --quiet --color auto --noprogressbar --needed --noconfirm \
+		debuginfod \
+		python-argparse-manpage \
+		python-build \
+		python-cryptography \
+		python-deprecated \
+		python-deprecation \
+		python-installer \
+		python-pyelftools \
+		python-jsonschema \
+		python-jsonschema-specifications \
+		python-pip \
+		python-setuptools \
+		python-uv \
+		python-virtualenv \
+		python-yaml \
+		rpcsvc-proto \
+		xorg-xlsclients \
+		yamllint
+
+	if ! [ "$?" = "0" ]; then
+		printf "pacman Install Error! [ general ]\n"
 		exit 1
 	fi
 
@@ -385,9 +421,6 @@ if which pacman &> /dev/null && [ -n "${is_arch}" ] || [ -n "${is_artix}" ]; the
 			patchelf \
 			pax \
 			pkgconf \
-			python-cryptography \
-			python-pyelftools \
-			python-jsonschema python-jsonschema-specifications \
 			readline \
 			rlwrap \
 			rpm-tools \
@@ -414,11 +447,11 @@ if which pacman &> /dev/null && [ -n "${is_arch}" ] || [ -n "${is_artix}" ]; the
 			whois \
 			xmlto \
 			xorg-server-xvfb \
-			yamllint \
 			zip \
 			zlib-ng \
 			zlib \
 			zstd
+
 		if ! [ "$?" = "0" ]; then
 			printf "pacman Install Error! [ dev ]\n"
 			exit 1
